runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: dist/argon-design-system-angular/index.html
  upload: dist/argon-design-system-angular/index.html
  secure: always

- url: /
  static_dir: dist/argon-design-system-angular
  secure: always

skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE