runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: dist/rcces-santa-cruz-queretaro/index.html
  upload: dist/rcces-santa-cruz-queretaro/index.html
  secure: always

- url: /
  static_dir: dist/rcces-santa-cruz-queretaro
  secure: always

skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE